//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 10:29:40 PM CEST 
//


package com.ftn.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EditAccomodationRequest }
     * 
     */
    public EditAccomodationRequest createEditAccomodationRequest() {
        return new EditAccomodationRequest();
    }

    /**
     * Create an instance of {@link AccomodationSoap }
     * 
     */
    public AccomodationSoap createAccomodationSoap() {
        return new AccomodationSoap();
    }

    /**
     * Create an instance of {@link RegisterAccomodationRequest }
     * 
     */
    public RegisterAccomodationRequest createRegisterAccomodationRequest() {
        return new RegisterAccomodationRequest();
    }

    /**
     * Create an instance of {@link DeleteAccomodationRequest }
     * 
     */
    public DeleteAccomodationRequest createDeleteAccomodationRequest() {
        return new DeleteAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationRequest }
     * 
     */
    public GetAccomodationRequest createGetAccomodationRequest() {
        return new GetAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsResponse }
     * 
     */
    public GetAllAccomodationsResponse createGetAllAccomodationsResponse() {
        return new GetAllAccomodationsResponse();
    }

    /**
     * Create an instance of {@link RegisterAccomodationResponse }
     * 
     */
    public RegisterAccomodationResponse createRegisterAccomodationResponse() {
        return new RegisterAccomodationResponse();
    }

    /**
     * Create an instance of {@link DeleteAccomodationResponse }
     * 
     */
    public DeleteAccomodationResponse createDeleteAccomodationResponse() {
        return new DeleteAccomodationResponse();
    }

    /**
     * Create an instance of {@link EditAccomodationResponse }
     * 
     */
    public EditAccomodationResponse createEditAccomodationResponse() {
        return new EditAccomodationResponse();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsRequest }
     * 
     */
    public GetAllAccomodationsRequest createGetAllAccomodationsRequest() {
        return new GetAllAccomodationsRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationResponse }
     * 
     */
    public GetAccomodationResponse createGetAccomodationResponse() {
        return new GetAccomodationResponse();
    }

    /**
     * Create an instance of {@link CitySoap }
     * 
     */
    public CitySoap createCitySoap() {
        return new CitySoap();
    }

    /**
     * Create an instance of {@link TypeAccomodationSoap }
     * 
     */
    public TypeAccomodationSoap createTypeAccomodationSoap() {
        return new TypeAccomodationSoap();
    }

    /**
     * Create an instance of {@link AgentSoap }
     * 
     */
    public AgentSoap createAgentSoap() {
        return new AgentSoap();
    }

    /**
     * Create an instance of {@link CountrySoap }
     * 
     */
    public CountrySoap createCountrySoap() {
        return new CountrySoap();
    }

    /**
     * Create an instance of {@link CategorySoap }
     * 
     */
    public CategorySoap createCategorySoap() {
        return new CategorySoap();
    }

}
