//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.26 at 08:51:35 AM CEST 
//


package com.ftn.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllAdditionalServicesRequest }
     * 
     */
    public GetAllAdditionalServicesRequest createGetAllAdditionalServicesRequest() {
        return new GetAllAdditionalServicesRequest();
    }

    /**
     * Create an instance of {@link CreateReservationAgentResponse }
     * 
     */
    public CreateReservationAgentResponse createCreateReservationAgentResponse() {
        return new CreateReservationAgentResponse();
    }

    /**
     * Create an instance of {@link GetAccomodationRoomsRequest }
     * 
     */
    public GetAccomodationRoomsRequest createGetAccomodationRoomsRequest() {
        return new GetAccomodationRoomsRequest();
    }

    /**
     * Create an instance of {@link DeleteRoomResponse }
     * 
     */
    public DeleteRoomResponse createDeleteRoomResponse() {
        return new DeleteRoomResponse();
    }

    /**
     * Create an instance of {@link EditAccomodationRequest }
     * 
     */
    public EditAccomodationRequest createEditAccomodationRequest() {
        return new EditAccomodationRequest();
    }

    /**
     * Create an instance of {@link AccomodationSoap }
     * 
     */
    public AccomodationSoap createAccomodationSoap() {
        return new AccomodationSoap();
    }

    /**
     * Create an instance of {@link GetAccomodationRoomsResponse }
     * 
     */
    public GetAccomodationRoomsResponse createGetAccomodationRoomsResponse() {
        return new GetAccomodationRoomsResponse();
    }

    /**
     * Create an instance of {@link RoomSoap }
     * 
     */
    public RoomSoap createRoomSoap() {
        return new RoomSoap();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServicesResponse }
     * 
     */
    public GetAllAdditionalServicesResponse createGetAllAdditionalServicesResponse() {
        return new GetAllAdditionalServicesResponse();
    }

    /**
     * Create an instance of {@link AdditionalServicesSoap }
     * 
     */
    public AdditionalServicesSoap createAdditionalServicesSoap() {
        return new AdditionalServicesSoap();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsResponse }
     * 
     */
    public GetAllAccomodationsResponse createGetAllAccomodationsResponse() {
        return new GetAllAccomodationsResponse();
    }

    /**
     * Create an instance of {@link EditRoomRequest }
     * 
     */
    public EditRoomRequest createEditRoomRequest() {
        return new EditRoomRequest();
    }

    /**
     * Create an instance of {@link GetAllMessagesResponse }
     * 
     */
    public GetAllMessagesResponse createGetAllMessagesResponse() {
        return new GetAllMessagesResponse();
    }

    /**
     * Create an instance of {@link MessageSoap }
     * 
     */
    public MessageSoap createMessageSoap() {
        return new MessageSoap();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link ConfirmReservationRequest }
     * 
     */
    public ConfirmReservationRequest createConfirmReservationRequest() {
        return new ConfirmReservationRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypesRequest }
     * 
     */
    public GetAllAccomodationTypesRequest createGetAllAccomodationTypesRequest() {
        return new GetAllAccomodationTypesRequest();
    }

    /**
     * Create an instance of {@link GetAllReservationsResponse }
     * 
     */
    public GetAllReservationsResponse createGetAllReservationsResponse() {
        return new GetAllReservationsResponse();
    }

    /**
     * Create an instance of {@link ReservationSoap }
     * 
     */
    public ReservationSoap createReservationSoap() {
        return new ReservationSoap();
    }

    /**
     * Create an instance of {@link DeleteAccomodationResponse }
     * 
     */
    public DeleteAccomodationResponse createDeleteAccomodationResponse() {
        return new DeleteAccomodationResponse();
    }

    /**
     * Create an instance of {@link RegisterRoomRequest }
     * 
     */
    public RegisterRoomRequest createRegisterRoomRequest() {
        return new RegisterRoomRequest();
    }

    /**
     * Create an instance of {@link GetAllAgentsResponse }
     * 
     */
    public GetAllAgentsResponse createGetAllAgentsResponse() {
        return new GetAllAgentsResponse();
    }

    /**
     * Create an instance of {@link AgentSoap }
     * 
     */
    public AgentSoap createAgentSoap() {
        return new AgentSoap();
    }

    /**
     * Create an instance of {@link RegisterAccomodationRequest }
     * 
     */
    public RegisterAccomodationRequest createRegisterAccomodationRequest() {
        return new RegisterAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAllCitiesRequest }
     * 
     */
    public GetAllCitiesRequest createGetAllCitiesRequest() {
        return new GetAllCitiesRequest();
    }

    /**
     * Create an instance of {@link DeleteRoomRequest }
     * 
     */
    public DeleteRoomRequest createDeleteRoomRequest() {
        return new DeleteRoomRequest();
    }

    /**
     * Create an instance of {@link GetAllPermissionsRequest }
     * 
     */
    public GetAllPermissionsRequest createGetAllPermissionsRequest() {
        return new GetAllPermissionsRequest();
    }

    /**
     * Create an instance of {@link GetAllCountriesRequest }
     * 
     */
    public GetAllCountriesRequest createGetAllCountriesRequest() {
        return new GetAllCountriesRequest();
    }

    /**
     * Create an instance of {@link CreatePriceListResponse }
     * 
     */
    public CreatePriceListResponse createCreatePriceListResponse() {
        return new CreatePriceListResponse();
    }

    /**
     * Create an instance of {@link PriceSoap }
     * 
     */
    public PriceSoap createPriceSoap() {
        return new PriceSoap();
    }

    /**
     * Create an instance of {@link CreateAnswerRequest }
     * 
     */
    public CreateAnswerRequest createCreateAnswerRequest() {
        return new CreateAnswerRequest();
    }

    /**
     * Create an instance of {@link CreatePriceListRequest }
     * 
     */
    public CreatePriceListRequest createCreatePriceListRequest() {
        return new CreatePriceListRequest();
    }

    /**
     * Create an instance of {@link GetRoomResponse }
     * 
     */
    public GetRoomResponse createGetRoomResponse() {
        return new GetRoomResponse();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypesResponse }
     * 
     */
    public GetAllAccomodationTypesResponse createGetAllAccomodationTypesResponse() {
        return new GetAllAccomodationTypesResponse();
    }

    /**
     * Create an instance of {@link TypeAccomodationSoap }
     * 
     */
    public TypeAccomodationSoap createTypeAccomodationSoap() {
        return new TypeAccomodationSoap();
    }

    /**
     * Create an instance of {@link EditAccomodationResponse }
     * 
     */
    public EditAccomodationResponse createEditAccomodationResponse() {
        return new EditAccomodationResponse();
    }

    /**
     * Create an instance of {@link RegisterRoomResponse }
     * 
     */
    public RegisterRoomResponse createRegisterRoomResponse() {
        return new RegisterRoomResponse();
    }

    /**
     * Create an instance of {@link GetAccomodationRequest }
     * 
     */
    public GetAccomodationRequest createGetAccomodationRequest() {
        return new GetAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAllReservationsRequest }
     * 
     */
    public GetAllReservationsRequest createGetAllReservationsRequest() {
        return new GetAllReservationsRequest();
    }

    /**
     * Create an instance of {@link CreateAnswerResponse }
     * 
     */
    public CreateAnswerResponse createCreateAnswerResponse() {
        return new CreateAnswerResponse();
    }

    /**
     * Create an instance of {@link ResponseSoap }
     * 
     */
    public ResponseSoap createResponseSoap() {
        return new ResponseSoap();
    }

    /**
     * Create an instance of {@link GetAllCitiesResponse }
     * 
     */
    public GetAllCitiesResponse createGetAllCitiesResponse() {
        return new GetAllCitiesResponse();
    }

    /**
     * Create an instance of {@link CitySoap }
     * 
     */
    public CitySoap createCitySoap() {
        return new CitySoap();
    }

    /**
     * Create an instance of {@link CreateReservationAgentRequest }
     * 
     */
    public CreateReservationAgentRequest createCreateReservationAgentRequest() {
        return new CreateReservationAgentRequest();
    }

    /**
     * Create an instance of {@link ReservationAgentSoap }
     * 
     */
    public ReservationAgentSoap createReservationAgentSoap() {
        return new ReservationAgentSoap();
    }

    /**
     * Create an instance of {@link GetAllMessagesRequest }
     * 
     */
    public GetAllMessagesRequest createGetAllMessagesRequest() {
        return new GetAllMessagesRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesResponse }
     * 
     */
    public GetAllCategoriesResponse createGetAllCategoriesResponse() {
        return new GetAllCategoriesResponse();
    }

    /**
     * Create an instance of {@link CategorySoap }
     * 
     */
    public CategorySoap createCategorySoap() {
        return new CategorySoap();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link UserSoap }
     * 
     */
    public UserSoap createUserSoap() {
        return new UserSoap();
    }

    /**
     * Create an instance of {@link GetAllRolesResponse }
     * 
     */
    public GetAllRolesResponse createGetAllRolesResponse() {
        return new GetAllRolesResponse();
    }

    /**
     * Create an instance of {@link RoleSoap }
     * 
     */
    public RoleSoap createRoleSoap() {
        return new RoleSoap();
    }

    /**
     * Create an instance of {@link GetAllRolesRequest }
     * 
     */
    public GetAllRolesRequest createGetAllRolesRequest() {
        return new GetAllRolesRequest();
    }

    /**
     * Create an instance of {@link RegisterAccomodationResponse }
     * 
     */
    public RegisterAccomodationResponse createRegisterAccomodationResponse() {
        return new RegisterAccomodationResponse();
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsRequest }
     * 
     */
    public GetAllAccomodationsRequest createGetAllAccomodationsRequest() {
        return new GetAllAccomodationsRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesRequest }
     * 
     */
    public GetAllCategoriesRequest createGetAllCategoriesRequest() {
        return new GetAllCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetRoomPricesRequest }
     * 
     */
    public GetRoomPricesRequest createGetRoomPricesRequest() {
        return new GetRoomPricesRequest();
    }

    /**
     * Create an instance of {@link DeleteAccomodationRequest }
     * 
     */
    public DeleteAccomodationRequest createDeleteAccomodationRequest() {
        return new DeleteAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAllReservationsAgentResponse }
     * 
     */
    public GetAllReservationsAgentResponse createGetAllReservationsAgentResponse() {
        return new GetAllReservationsAgentResponse();
    }

    /**
     * Create an instance of {@link GetAllPermissionsResponse }
     * 
     */
    public GetAllPermissionsResponse createGetAllPermissionsResponse() {
        return new GetAllPermissionsResponse();
    }

    /**
     * Create an instance of {@link PermissionSoap }
     * 
     */
    public PermissionSoap createPermissionSoap() {
        return new PermissionSoap();
    }

    /**
     * Create an instance of {@link GetAllReservationsAgentRequest }
     * 
     */
    public GetAllReservationsAgentRequest createGetAllReservationsAgentRequest() {
        return new GetAllReservationsAgentRequest();
    }

    /**
     * Create an instance of {@link GetAllResponsesResponse }
     * 
     */
    public GetAllResponsesResponse createGetAllResponsesResponse() {
        return new GetAllResponsesResponse();
    }

    /**
     * Create an instance of {@link GetRoomPricesResponse }
     * 
     */
    public GetRoomPricesResponse createGetRoomPricesResponse() {
        return new GetRoomPricesResponse();
    }

    /**
     * Create an instance of {@link GetAllCountriesResponse }
     * 
     */
    public GetAllCountriesResponse createGetAllCountriesResponse() {
        return new GetAllCountriesResponse();
    }

    /**
     * Create an instance of {@link CountrySoap }
     * 
     */
    public CountrySoap createCountrySoap() {
        return new CountrySoap();
    }

    /**
     * Create an instance of {@link GetAllResponsesRequest }
     * 
     */
    public GetAllResponsesRequest createGetAllResponsesRequest() {
        return new GetAllResponsesRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationResponse }
     * 
     */
    public GetAccomodationResponse createGetAccomodationResponse() {
        return new GetAccomodationResponse();
    }

    /**
     * Create an instance of {@link EditRoomResponse }
     * 
     */
    public EditRoomResponse createEditRoomResponse() {
        return new EditRoomResponse();
    }

    /**
     * Create an instance of {@link GetAllAgentsRequest }
     * 
     */
    public GetAllAgentsRequest createGetAllAgentsRequest() {
        return new GetAllAgentsRequest();
    }

    /**
     * Create an instance of {@link GetRoomRequest }
     * 
     */
    public GetRoomRequest createGetRoomRequest() {
        return new GetRoomRequest();
    }

}
