//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.21 at 10:59:52 PM CEST 
//


package com.ftn.webservice.files;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clientStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="clientStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AKTIVAN"/&gt;
 *     &lt;enumeration value="NEAKTIVAN"/&gt;
 *     &lt;enumeration value="BLOKIRAN"/&gt;
 *     &lt;enumeration value="UKLONJEN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "clientStatus")
@XmlEnum
public enum ClientStatus {

    AKTIVAN,
    NEAKTIVAN,
    BLOKIRAN,
    UKLONJEN;

    public String value() {
        return name();
    }

    public static ClientStatus fromValue(String v) {
        return valueOf(v);
    }

}
