//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 09:31:39 PM CEST 
//


package com.ftn.webservice.files;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.webservice.files package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.webservice.files
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterAccomodationRequest }
     * 
     */
    public RegisterAccomodationRequest createRegisterAccomodationRequest() {
        return new RegisterAccomodationRequest();
    }

    /**
     * Create an instance of {@link AccomodationSoap }
     * 
     */
    public AccomodationSoap createAccomodationSoap() {
        return new AccomodationSoap();
    }

    /**
     * Create an instance of {@link RegisterAccomodationResponse }
     * 
     */
    public RegisterAccomodationResponse createRegisterAccomodationResponse() {
        return new RegisterAccomodationResponse();
    }

    /**
     * Create an instance of {@link DeleteAccomodationRequest }
     * 
     */
    public DeleteAccomodationRequest createDeleteAccomodationRequest() {
        return new DeleteAccomodationRequest();
    }

    /**
     * Create an instance of {@link DeleteAccomodationResponse }
     * 
     */
    public DeleteAccomodationResponse createDeleteAccomodationResponse() {
        return new DeleteAccomodationResponse();
    }

    /**
     * Create an instance of {@link EditAccomodationRequest }
     * 
     */
    public EditAccomodationRequest createEditAccomodationRequest() {
        return new EditAccomodationRequest();
    }

    /**
     * Create an instance of {@link EditAccomodationResponse }
     * 
     */
    public EditAccomodationResponse createEditAccomodationResponse() {
        return new EditAccomodationResponse();
    }

    /**
     * Create an instance of {@link GetAccomodationRequest }
     * 
     */
    public GetAccomodationRequest createGetAccomodationRequest() {
        return new GetAccomodationRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationResponse }
     * 
     */
    public GetAccomodationResponse createGetAccomodationResponse() {
        return new GetAccomodationResponse();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsRequest }
     * 
     */
    public GetAllAccomodationsRequest createGetAllAccomodationsRequest() {
        return new GetAllAccomodationsRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationsResponse }
     * 
     */
    public GetAllAccomodationsResponse createGetAllAccomodationsResponse() {
        return new GetAllAccomodationsResponse();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServicesRequest }
     * 
     */
    public GetAllAdditionalServicesRequest createGetAllAdditionalServicesRequest() {
        return new GetAllAdditionalServicesRequest();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServicesResponse }
     * 
     */
    public GetAllAdditionalServicesResponse createGetAllAdditionalServicesResponse() {
        return new GetAllAdditionalServicesResponse();
    }

    /**
     * Create an instance of {@link AdditionalServicesSoap }
     * 
     */
    public AdditionalServicesSoap createAdditionalServicesSoap() {
        return new AdditionalServicesSoap();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypesRequest }
     * 
     */
    public GetAllAccomodationTypesRequest createGetAllAccomodationTypesRequest() {
        return new GetAllAccomodationTypesRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypesResponse }
     * 
     */
    public GetAllAccomodationTypesResponse createGetAllAccomodationTypesResponse() {
        return new GetAllAccomodationTypesResponse();
    }

    /**
     * Create an instance of {@link TypeAccomodationSoap }
     * 
     */
    public TypeAccomodationSoap createTypeAccomodationSoap() {
        return new TypeAccomodationSoap();
    }

    /**
     * Create an instance of {@link GetAllCategoriesRequest }
     * 
     */
    public GetAllCategoriesRequest createGetAllCategoriesRequest() {
        return new GetAllCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesResponse }
     * 
     */
    public GetAllCategoriesResponse createGetAllCategoriesResponse() {
        return new GetAllCategoriesResponse();
    }

    /**
     * Create an instance of {@link CategorySoap }
     * 
     */
    public CategorySoap createCategorySoap() {
        return new CategorySoap();
    }

    /**
     * Create an instance of {@link GetAllCitiesRequest }
     * 
     */
    public GetAllCitiesRequest createGetAllCitiesRequest() {
        return new GetAllCitiesRequest();
    }

    /**
     * Create an instance of {@link GetAllCitiesResponse }
     * 
     */
    public GetAllCitiesResponse createGetAllCitiesResponse() {
        return new GetAllCitiesResponse();
    }

    /**
     * Create an instance of {@link CitySoap }
     * 
     */
    public CitySoap createCitySoap() {
        return new CitySoap();
    }

    /**
     * Create an instance of {@link GetAccomodationRoomsRequest }
     * 
     */
    public GetAccomodationRoomsRequest createGetAccomodationRoomsRequest() {
        return new GetAccomodationRoomsRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationRoomsResponse }
     * 
     */
    public GetAccomodationRoomsResponse createGetAccomodationRoomsResponse() {
        return new GetAccomodationRoomsResponse();
    }

    /**
     * Create an instance of {@link RoomSoap }
     * 
     */
    public RoomSoap createRoomSoap() {
        return new RoomSoap();
    }

    /**
     * Create an instance of {@link GetAllAgentsRequest }
     * 
     */
    public GetAllAgentsRequest createGetAllAgentsRequest() {
        return new GetAllAgentsRequest();
    }

    /**
     * Create an instance of {@link GetAllAgentsResponse }
     * 
     */
    public GetAllAgentsResponse createGetAllAgentsResponse() {
        return new GetAllAgentsResponse();
    }

    /**
     * Create an instance of {@link AgentSoap }
     * 
     */
    public AgentSoap createAgentSoap() {
        return new AgentSoap();
    }

    /**
     * Create an instance of {@link GetAllCountriesRequest }
     * 
     */
    public GetAllCountriesRequest createGetAllCountriesRequest() {
        return new GetAllCountriesRequest();
    }

    /**
     * Create an instance of {@link GetAllCountriesResponse }
     * 
     */
    public GetAllCountriesResponse createGetAllCountriesResponse() {
        return new GetAllCountriesResponse();
    }

    /**
     * Create an instance of {@link CountrySoap }
     * 
     */
    public CountrySoap createCountrySoap() {
        return new CountrySoap();
    }

}
