//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 04:52:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.com/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ftn.webservice.files;
