spring:
  application:
    name: eureka-server

server:
  port: 8761
  ssl:
    enabled: true
    client-auth: need
    key-store: eureka.p12
    key-store-password: eureka
    key-alias: eureka
    trust-store: eureka.p12
    trust-store-password: eureka
    
eureka:
  instance:
    securePort: ${server.port}
    securePortEnabled: true
    prefer-ip-address: true
    nonSecurePortEnabled: false 
  client:
    registerWithEureka: false
    fetchRegistry: false